version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/source/bank_account/
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 150
      runas: root
  AfterInstall: 
    - location: scripts/build.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 150
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 150
      runas: root