version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/bank_account/
hooks:
  BeforeInstall:
    - location: clean.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 150
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 150
      runas: root