version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew test 
  post_build:
    commands:
      - echo Build completed on `date`
      - ./gradlew bootJar
artifacts:
  files:
    - build/libs/bank_account_management-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  name: bank-account-management
  discard-paths: yes